### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by aurimrv** [xybu/onedrive-d-old#100]
Dear Xybu

I am trying to install 1.0-dev version of onedrive-d on Ubuntu 14.04, but I am getting the following error message:

auri@inct:~/temp$ git clone https://github.com/xybu/onedrive-d.git
Cloning into 'onedrive-d'...
remote: Counting objects: 819, done.
remote: Total 819 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (819/819), 255.40 KiB | 221.00 KiB/s, done.
Resolving deltas: 100% (420/420), done.
Checking connectivity... done.
auri@inct:~/temp$ cd onedrive-d/
auri@inct:~/temp/onedrive-d$ ./onedrive_d/setup.py
bash: ./onedrive_d/setup.py: Permissão negada
auri@inct:~/temp/onedrive-d$ python3 ./onedrive_d/setup.py 
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
auri@inct:~/temp/onedrive-d$ 

Please, may you help me?

**Comment by xybu** [comment]
``` bash
./setup.sh inst
```

No need to run `setup.py` yourself.

**Comment by aurimrv** [comment]
Ok, I try this but now Linux cannot find no executable onedrive-d or onedrive-pref

---

auri@inct:~/temp/onedrive-d$ ./setup.sh inst
Lendo listas de pacotes... Pronto
Construindo árvore de dependências  
Lendo informação de estado... Pronto
git já é a versão mais nova.
inotify-tools já é a versão mais nova.
python3-pip já é a versão mais nova.
python3-gi já é a versão mais nova.
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.
running install
Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating onedrive_d.egg-info
writing requirements to onedrive_d.egg-info/requires.txt
writing onedrive_d.egg-info/PKG-INFO
writing top-level names to onedrive_d.egg-info/top_level.txt
writing dependency_links to onedrive_d.egg-info/dependency_links.txt
writing manifest file 'onedrive_d.egg-info/SOURCES.txt'
warning: manifest_maker: standard file 'setup.py' not found

reading manifest file 'onedrive_d.egg-info/SOURCES.txt'
writing manifest file 'onedrive_d.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/onedrive_d
copying onedrive_d/config.py -> build/lib/onedrive_d
copying onedrive_d/pref_cmd.py -> build/lib/onedrive_d
copying onedrive_d/observer_gtk.py -> build/lib/onedrive_d
copying onedrive_d/pref_gtk.py -> build/lib/onedrive_d
copying onedrive_d/pref.py -> build/lib/onedrive_d
copying onedrive_d/daemon.py -> build/lib/onedrive_d
copying onedrive_d/logger.py -> build/lib/onedrive_d
copying onedrive_d/setup.py -> build/lib/onedrive_d
copying onedrive_d/**init**.py -> build/lib/onedrive_d
copying onedrive_d/live_api.py -> build/lib/onedrive_d
copying onedrive_d/main.py -> build/lib/onedrive_d
creating build/lib/onedrive_d/res
copying onedrive_d/res/icon_256.png -> build/lib/onedrive_d/res
copying onedrive_d/res/icon_256_idle.png -> build/lib/onedrive_d/res
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/config.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/pref_cmd.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/observer_gtk.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/pref_gtk.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/pref.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/daemon.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/logger.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/setup.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/**init**.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/live_api.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/main.py -> build/bdist.linux-x86_64/egg/onedrive_d
creating build/bdist.linux-x86_64/egg/onedrive_d/res
copying build/lib/onedrive_d/res/icon_256.png -> build/bdist.linux-x86_64/egg/onedrive_d/res
copying build/lib/onedrive_d/res/icon_256_idle.png -> build/bdist.linux-x86_64/egg/onedrive_d/res
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/config.py to config.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/pref_cmd.py to pref_cmd.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/observer_gtk.py to observer_gtk.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/pref_gtk.py to pref_gtk.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/pref.py to pref.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/daemon.py to daemon.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/logger.py to logger.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/setup.py to setup.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/**init**.py to **init**.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/live_api.py to live_api.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/main.py to main.cpython-34.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
onedrive_d.**pycache**.setup.cpython-34: module references **file**
onedrive_d.**pycache**.observer_gtk.cpython-34: module references **file**
creating dist
creating 'dist/onedrive_d-1.0_dev-py3.4.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing onedrive_d-1.0_dev-py3.4.egg
removing '/usr/local/lib/python3.4/dist-packages/onedrive_d-1.0_dev-py3.4.egg' (and everything under it)
creating /usr/local/lib/python3.4/dist-packages/onedrive_d-1.0_dev-py3.4.egg
Extracting onedrive_d-1.0_dev-py3.4.egg to /usr/local/lib/python3.4/dist-packages
onedrive-d 1.0-dev is already the active version in easy-install.pth

Installed /usr/local/lib/python3.4/dist-packages/onedrive_d-1.0_dev-py3.4.egg
Processing dependencies for onedrive-d==1.0-dev
Searching for Send2Trash==1.3.0
Best match: Send2Trash 1.3.0
Processing Send2Trash-1.3.0-py3.4.egg
Send2Trash 1.3.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.4/dist-packages/Send2Trash-1.3.0-py3.4.egg
Searching for certifi==14.05.14
Best match: certifi 14.05.14
Processing certifi-14.05.14-py3.4.egg
certifi 14.05.14 is already the active version in easy-install.pth

Using /usr/local/lib/python3.4/dist-packages/certifi-14.05.14-py3.4.egg
Searching for urllib3==1.7.1
Best match: urllib3 1.7.1
urllib3 1.7.1 is already the active version in easy-install.pth

Using /usr/lib/python3/dist-packages
Searching for requests==2.2.1
Best match: requests 2.2.1
requests 2.2.1 is already the active version in easy-install.pth

Using /usr/lib/python3/dist-packages
Finished processing dependencies for onedrive-d==1.0-dev
running clean

Please issue command 'onedrive-pref [--no-gui]' to configure the app,
and then issue command 'onedrive-d' to start the daemon.
All operations finished.
auri@inct:~/temp/onedrive-d$ onedrive-pref --no-gui
onedrive-pref: comando não encontrado
auri@inct:~/temp/onedrive-d$

**Comment by xybu** [comment]
#65

**Comment by aurimrv** [comment]
As I undertood in the issue #65 it is requested to run the command

./onedrive_d/setup.py

directly but that I got the message I sent you before, isn't it?

**Comment by xybu** [comment]
It is requested to run `main.py` or `pref.py` directly.

**Comment by aurimrv** [comment]
Does main.py corresponds to onedrive-d and pref.py corresponds to onedrive-pref commands?

**Comment by xybu** [comment]
Yes

**Comment by aurimrv** [comment]
Ok, so to start the sync after a new boot I need to start

python3 main.py
or 
main.py

Is this correct?

**Comment by xybu** [comment]
Yes.

Sincerely,Xiangyu Bu

Date: Thu, 8 Jan 2015 15:43:20 -0800

**Comment by aurimrv** [comment]
Thank you very much and congratulations by your effort on development of this tool.

Best regards
Cheers
