### ISSUE TITLE
Problem with the gui (in lubuntu 14.04)

### ISSUE THREAD

**Issue by fboumol** [xybu/onedrive-d-old#104]
The gui is not working for me (using lubuntu 14.04). As far as I see more people has had the same problem https://github.com/xybu/onedrive-d/issues/55

I suspect I could make it work form the command line (without gui) if I I am able to write down the details of my account in the file ~/.onedrive/user.conf

Can anyone upload an example of how looks like this file (use the settings of a false microsoft account in the uploaded file) or tell me where to find one such file?

**Comment by xybu** [comment]
I haven't implemented GUI.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by fboumol** [comment]
Thanks for the answer, but is it possible to take a look at an example of a file  ~/.onedrive/user.conf ?

This is what it is about my previous question.

**Comment by xybu** [comment]
May you try `./onedrive_d/pref.py --no-gui` to generate the conf file?

**Comment by fboumol** [comment]
Unfortunately it is not working neither.

I had to use I computer with ubuntu (instead of lubuntu) to generate the conf file, and not it is working.
