### ISSUE TITLE
attempt to unlock mutex error

### ISSUE THREAD

**Issue by romain-nio** [xybu/onedrive-d-old#105]
Hi,

Recently installed onedrive-d, I faced an error on ubuntu 14.04 :
$ onedrive-prefs --no-gui
Attempt to unlock mutex that was not locked
Aborted (core dumped)

**Comment by smackalino** [comment]
Me too... any word?

**Comment by xybu** [comment]
"installed"? For 1.0-dev how were you able to run by command `onedrive-prefs`? I didn't even have shortcuts created.

But anyway, it seems a GUI (not sure without knowing the version) was to be built but GTK+ library has that bug. The GTK+ bug is still unsolved as of now from Launchpad.
