### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Lak4CYUT** [xybu/onedrive-d-old#106]
1. I cannot install onedrive_d in ubuntu 14.04.
   Below is my log,

lak@Mason-Ubuntu:~/onedrive-d-1.0-dev$ sudo ./setup.sh inst
正在讀取套件清單... 完成
正在重建相依關係  
正在讀取狀態資料... 完成
inotify-tools 已是最新版本。
python3-pip 已是最新版本。
git 已是最新版本。
python3-gi 已是最新版本。
以下套件為自動安裝，並且已經無用：
  firefox-locale-zh-hant gir1.2-gdesktopenums-3.0 gir1.2-gnomedesktop-3.0
  gnome-shell-common libfm-data libfm-extra4 libfm-gtk-data libfm-gtk4
  libfm-modules libfm4 libmenu-cache-bin libmenu-cache3 libtcl8.5
  linux-image-3.13.0-30-generic linux-image-extra-3.13.0-30-generic
  linux-signed-image-3.13.0-30-generic lxmenu-data tcl8.5
Use 'apt-get autoremove' to remove them.
升級 0 個，新安裝 0 個，移除 0 個，有 18 個未被升級。
/usr/local/lib/python3.4/dist-packages/setuptools-12.0.5-py3.4.egg/setuptools/dist.py:283: UserWarning: The version specified requires normalization, consider using '1.0.dev0' instead of '1.0-dev'.
running install
Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files
/usr/local/lib/python3.4/dist-packages/setuptools-12.0.5-py3.4.egg/pkg_resources/**init**.py:2510: PEP440Warning: 'ufw (0.34-rc-0ubuntu2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python3.4/dist-packages/setuptools-12.0.5-py3.4.egg/pkg_resources/**init**.py:2510: PEP440Warning: 'xdiagnose (3.6.3build2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python3.4/dist-packages/setuptools-12.0.5-py3.4.egg/pkg_resources/**init**.py:2510: PEP440Warning: 'apturl (0.5.2ubuntu4)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python3.4/dist-packages/setuptools-12.0.5-py3.4.egg/pkg_resources/**init**.py:2510: PEP440Warning: 'python-debian (0.1.21-nmu2ubuntu2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python3.4/dist-packages/setuptools-12.0.5-py3.4.egg/pkg_resources/**init**.py:2510: PEP440Warning: 'python-apt (0.9.3.5ubuntu1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
running bdist_egg
running egg_info
creating onedrive_d.egg-info
writing requirements to onedrive_d.egg-info/requires.txt
writing top-level names to onedrive_d.egg-info/top_level.txt
writing onedrive_d.egg-info/PKG-INFO
writing dependency_links to onedrive_d.egg-info/dependency_links.txt
writing manifest file 'onedrive_d.egg-info/SOURCES.txt'
warning: manifest_maker: standard file 'setup.py' not found

reading manifest file 'onedrive_d.egg-info/SOURCES.txt'
writing manifest file 'onedrive_d.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/onedrive_d
copying onedrive_d/logger.py -> build/lib/onedrive_d
copying onedrive_d/live_api.py -> build/lib/onedrive_d
copying onedrive_d/setup.py -> build/lib/onedrive_d
copying onedrive_d/pref_cmd.py -> build/lib/onedrive_d
copying onedrive_d/pref.py -> build/lib/onedrive_d
copying onedrive_d/**init**.py -> build/lib/onedrive_d
copying onedrive_d/pref_gtk.py -> build/lib/onedrive_d
copying onedrive_d/observer_gtk.py -> build/lib/onedrive_d
copying onedrive_d/main.py -> build/lib/onedrive_d
copying onedrive_d/daemon.py -> build/lib/onedrive_d
copying onedrive_d/config.py -> build/lib/onedrive_d
creating build/lib/onedrive_d/res
copying onedrive_d/res/icon_256_idle.png -> build/lib/onedrive_d/res
copying onedrive_d/res/icon_256.png -> build/lib/onedrive_d/res
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/logger.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/live_api.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/setup.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/pref_cmd.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/pref.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/**init**.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/pref_gtk.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/observer_gtk.py -> build/bdist.linux-x86_64/egg/onedrive_d
creating build/bdist.linux-x86_64/egg/onedrive_d/res
copying build/lib/onedrive_d/res/icon_256_idle.png -> build/bdist.linux-x86_64/egg/onedrive_d/res
copying build/lib/onedrive_d/res/icon_256.png -> build/bdist.linux-x86_64/egg/onedrive_d/res
copying build/lib/onedrive_d/main.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/daemon.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/config.py -> build/bdist.linux-x86_64/egg/onedrive_d
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/logger.py to logger.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/live_api.py to live_api.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/setup.py to setup.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/pref_cmd.py to pref_cmd.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/pref.py to pref.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/**init**.py to **init**.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/pref_gtk.py to pref_gtk.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/observer_gtk.py to observer_gtk.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/main.py to main.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/daemon.py to daemon.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/config.py to config.cpython-34.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
onedrive_d.**pycache**.observer_gtk.cpython-34: module references **file**
onedrive_d.**pycache**.setup.cpython-34: module references **file**
creating dist
creating 'dist/onedrive_d-1.0.dev0-py3.4.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing onedrive_d-1.0.dev0-py3.4.egg
Removing /usr/local/lib/python3.4/dist-packages/onedrive_d-1.0.dev0-py3.4.egg
creating /usr/local/lib/python3.4/dist-packages/onedrive_d-1.0.dev0-py3.4.egg
Extracting onedrive_d-1.0.dev0-py3.4.egg to /usr/local/lib/python3.4/dist-packages
onedrive-d 1.0.dev0 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.4/dist-packages/onedrive_d-1.0.dev0-py3.4.egg
Processing dependencies for onedrive-d==1.0.dev0
Searching for Send2Trash==1.3.0
Best match: Send2Trash 1.3.0
Processing Send2Trash-1.3.0-py3.4.egg
Send2Trash 1.3.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.4/dist-packages/Send2Trash-1.3.0-py3.4.egg
Searching for certifi==14.5.14
Best match: certifi 14.5.14
Processing certifi-14.05.14-py3.4.egg
certifi 14.5.14 is already the active version in easy-install.pth

Using /usr/local/lib/python3.4/dist-packages/certifi-14.05.14-py3.4.egg
Searching for urllib3==1.7.1
Best match: urllib3 1.7.1
Adding urllib3 1.7.1 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for requests==2.2.1
Best match: requests 2.2.1
requests 2.2.1 is already the active version in easy-install.pth

Using /usr/lib/python3/dist-packages
Finished processing dependencies for onedrive-d==1.0.dev0
/usr/local/lib/python3.4/dist-packages/setuptools-12.0.5-py3.4.egg/setuptools/dist.py:283: UserWarning: The version specified requires normalization, consider using '1.0.dev0' instead of '1.0-dev'.
running clean
mkdir: 無法建立目錄‘/home/lak/.onedrive’: 檔案已存在
lak@Mason-Ubuntu:~/onedrive-d-1.0-dev$ onedrive_d
onedrive_d：Command not found
1. Remove problem, because I have install Python2 and 3, so when execute ./setup.sh remove will cause some problem as the following, 

lak@Mason-Ubuntu:~/onedrive-d-1.0-dev$ ./setup.sh remove
Removing Python 2 version of onedrive_d, if any.
Cannot uninstall requirement onedrive-d, not installed
Storing debug log for failure in /home/lak/.pip/pip.log
lak@Mason-Ubuntu:~/onedrive-d-1.0-dev$ ubuntu

**Comment by xybu** [comment]
Remove directory `/home/lak/.onedrive` and try again. For starting the program (command not found), refer to #65.
