### ISSUE TITLE
Corrupted files on Windows 8.1 OneDrive

### ISSUE THREAD

**Issue by ahogen** [xybu/onedrive-d-old#108]
Hi, all,

<b>Problem:</b>
I recently installed onedrive-d on my Linux Mint machine (Rebecca with Cinnamon). It seemed to be working okay. Let it do its thing for about a day. I had connected it to the same folder my Windows 7 partition uses for OneDrive so it wouldn't have to sync anything. It should have only needed to update a handful of files. It ended up grabbing a bunch and doing it's renaming dance, which was rather annoying, but I went with it.

Shortly after (maybe a day?), I noticed that OneDrive on my Win 8.1 laptop wasn't working at all. Major deal, since I rely on it to sync files between my two computers and the cloud, so I can have my school documents available anywhere. The regular OneDrive/Skydrive logo did not appear in my taskbar at all. If I ran the OneDrive Metro app, it would display its splash screen, pretend like it was loading (the stupid "loading" bubbles/dots flying around up top) and then would simply close.

I've spent the last 2-3 days trying to fix this issue and I just found a solution. Here are somethings I've tried that have <b>not</b> worked...
- Restarted pc
- Reset OneDrive using the Microsoft Diagnostics tool
- System Restore
- System Refresh
- Disabled/Enabled OneDrive services via the registry
- Disconnected/Reconnected my account
  ...like I said, none of those options worked.

<b>Solution:</b>

Stupid as heck. I copied all files in the folder to a new folder and found out that the "desktop.ini" file (which was previously hidden) was corrupted. I deleted the file from the original (now empty) OneDrive folder and tried to open OneDrive again and IT WORKED!

As I was copying my original files back, so OneDrive wouldn't download as much, I found a few corrupted files in the mix (see picture below). Like everyone else has said, the pics greater than or equal to [whatever dimensions it is] were corrupted, but also, there was an Excel spread sheet and a PDF in the mix. The PDF contained sensitive info, but the Excel file and one of the pictures did not. I am perfectly willing to share those corrupted files with someone for analysis so that onedrive-d can be patched up.
![onedrive copy error](https://cloud.githubusercontent.com/assets/6827790/5991523/dde5f0f4-a9a8-11e4-95f8-717dfdd94f80.PNG)

Anyway, I hope that helps somebody out. Unfortunately, I won't be using onedrive-d any more. I just can't afford to get locked out of my desktop app like that.

Great application. Thanks for putting it together! Honestly, I thought I'd never see something like this for Linux to interface with a Microsoft web/server application. :)

**Comment by xybu** [comment]
I thought desktop.ini is in the exclusion list of Microsoft OneDrive client on W8.1. I added it to to onedrive-d exclusion list. No idea how that file was modified, but hopefully that will stop the bug from propagating.

**Comment by ahogen** [comment]
Oh okay. Yeah, that would screw things up...

I wish I could help test it for you, but I can't let my college reports get corrupted. Sorry. :-)
