### ISSUE TITLE
onedrive-d re-upload files every boot

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [xybu/onedrive-d-old#112]
See
mk-fg/python-onedrive#49

**Comment by mk-fg** [comment]
```
Every time i boot, i have onedrive-d at startup,
my upload band get saturated and the notification
applet get spammed by messages (see attached image).

The folder syncronized contains a symlink to a folder in a ntfs partition.
```

Image link from the last comment doesn't seem to work for me though - says 403 Forbidden, not sure if maybe it should.

**Comment by xybu** [comment]
Which version are you at? Intuitively it may be 0.8 something.

**Comment by Alessandro-Barbieri** [comment]
@xybu Don't know, how i discover?
@mk-fg I reuploaded the image.

**Comment by xybu** [comment]
If you can run the program by command `onedrive-d` then its version is sure under 1.0 (the version 1.0-dev doesn't attach itself to the system so it can get deleted more easily).

**Comment by Alessandro-Barbieri** [comment]
It also spammed copies

 ls  
04120001.JPG
04120001.JPG (OLDER_1074612826.0)
04120001.JPG (OLDER_1074612826.0) (OLDER_1074612826.0)
04120001.JPG (OLDER_1074612826.0) (OLDER_1074612826.0) (OLDER_1074612826.0)
04120001.JPG (OLDER_1074612826.0) (OLDER_1074612826.0) (OLDER_1074612826.0) (OLDER_1074612826.0)
04120001.JPG (OLDER_1074612826.0) (OLDER_1074612826.0) (OLDER_1074612826.0) (OLDER_1074612826.0) (OLDER_1074612826.0)
04120002.JPG
04120002.JPG (OLDER_1074612844.0)
04120002.JPG (OLDER_1074612844.0) (OLDER_1074612844.0)
04120002.JPG (OLDER_1074612844.0) (OLDER_1074612844.0) (OLDER_1074612844.0)
04120002.JPG (OLDER_1074612844.0) (OLDER_1074612844.0) (OLDER_1074612844.0) (OLDER_1074612844.0)
04120002.JPG (OLDER_1074612844.0) (OLDER_1074612844.0) (OLDER_1074612844.0) (OLDER_1074612844.0) (OLDER_1074612844.0)
04120003.JPG
04120003.JPG (OLDER_1074612864.0)
04120003.JPG (OLDER_1074612864.0) (OLDER_1074612864.0)
04120003.JPG (OLDER_1074612864.0) (OLDER_1074612864.0) (OLDER_1074612864.0)
04120003.JPG (OLDER_1074612864.0) (OLDER_1074612864.0) (OLDER_1074612864.0) (OLDER_1074612864.0)
04120003.JPG (OLDER_1074612864.0) (OLDER_1074612864.0) (OLDER_1074612864.0) (OLDER_1074612864.0) (OLDER_1074612864.0)
04120005.JPG
04120005.JPG (OLDER_1074612882.0)
04120005.JPG (OLDER_1074612882.0) (OLDER_1074612882.0)
04120005.JPG (OLDER_1074612882.0) (OLDER_1074612882.0) (OLDER_1074612882.0)
04120005.JPG (OLDER_1074612882.0) (OLDER_1074612882.0) (OLDER_1074612882.0) (OLDER_1074612882.0)
04120005.JPG (OLDER_1074612882.0) (OLDER_1074612882.0) (OLDER_1074612882.0) (OLDER_1074612882.0) (OLDER_1074612882.0)
04120007.JPG
04120007.JPG (OLDER_1074612902.0)
04120007.JPG (OLDER_1074612902.0) (OLDER_1074612902.0)
04120007.JPG (OLDER_1074612902.0) (OLDER_1074612902.0) (OLDER_1074612902.0)
04120007.JPG (OLDER_1074612902.0) (OLDER_1074612902.0) (OLDER_1074612902.0) (OLDER_1074612902.0)
04120007.JPG (OLDER_1074612902.0) (OLDER_1074612902.0) (OLDER_1074612902.0) (OLDER_1074612902.0) (OLDER_1074612902.0)

**Comment by Alessandro-Barbieri** [comment]
The version i use is this
https://github.com/xybu92/onedrive-d/archive/master.zip
I'm trying to use latest but i found some trouble.
#65 #66 #113

**Comment by shekharmittal** [comment]
+1 I am facing the same issue. 

-rw-rw-r--  1 shekhar shekhar 40501 Feb 13 09:21 harris_school_degree.PDF
-rw-rw-r--  1 shekhar shekhar 40501 Feb 13 09:43 harris_school_degree.PDF (OLDER_1375678518.0)
-rw-rw-r--  1 shekhar shekhar 40501 Feb 13 12:13 harris_school_degree.PDF (OLDER_1375678518.0) (OLDER_1375678518.0)
-rw-rw-r--  1 shekhar shekhar 40501 Feb 15 11:00 harris_school_degree.PDF (OLDER_1375678518.0) (OLDER_1375678518.0) (OLDER_1375678518.0)
-rw-rw-r--  1 shekhar shekhar 40501 Aug  4  2013 harris_school_degree.PDF (OLDER_1375678518.0) (OLDER_1375678518.0) (OLDER_1375678518.0) (OLDER_1375678518.0)

**Comment by xybu** [comment]
Use 1.0-dev. At least please stop using 0.8 or 0.85.

Sent from my Windows Phone

**Comment by Alessandro-Barbieri** [comment]
Old guides still point to master, like this
http://www.tuxjournal.net/microsoft-onedrive-ubuntu-sincronizzazione-possibile/

We can close this if 0.8\* will not be supported anymore.

**Comment by shekharmittal** [comment]
And this
http://www.omgubuntu.co.uk/2014/06/one-drive-ubuntu-integration

**Comment by xybu** [comment]
Because I don't have control over those articles, I deleted `master` branch. That version doesn't track file mtime properties well (there is inconsistency between mtime reported by server and reported by OS; without database we simply couldn't solve it). Sorry for the mess it causes.

Honestly since last August I have extremely limited time to support this project, and I have been extremely sorry for leaving those bugs unsolved while making slow progress on future versions. The bugs on 1.0-dev are architectural, `future` branch aims to solve all of them as a whole but I am too slow.

**Comment by shekharmittal** [comment]
One last thing. How do I upgrade this application?
Any specific instructions?

**Comment by xybu** [comment]
Uninstall as #113 says
Download src code from 1.0-dev branch
Run `./setup.sh inst`
Note that the program won't attach itself to the system. You need to run the script manually as #65 discussed.
