### ISSUE TITLE
Uninstall onedrive-d < 1.0

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [xybu/onedrive-d-old#113]
/usr/local/bin/onedrive-cli
/usr/local/bin/onedrive-d
/usr/local/bin/onedrive-prefs

are still there after uninstall

**Comment by xybu** [comment]
Try if these commands will fully uninstall the program:

```
# kill the processes if they are running
killall -9 onedrive-d
killall -9 inotifywait
killall -9 python
# use pip to uninstall the program
sudo pip uninstall onedrive-d
# delete config files
rm -rv ~/.onedrive
```

`pip` should take care of removing those shortcuts.
