### ISSUE TITLE
No notifications Elementary OS Freya

### ISSUE THREAD

**Issue by tcass1977** [xybu/onedrive-d-old#120]
Everything seems to sync properly but I have no notifications.  Do not know what to install or if I need to install anything.  However, all my files synced properly, i ran setup from CLI.  Just don't know where to look for notifications.  Most likely my fault but thought I would drop a line and say thank you for your work.
And if you knew or someone else had any input.

alliedbass

**Comment by xybu** [comment]
CLI prints log to, by default, stderr. You can change log severity level by --log argument. Need to double check if log path can be configured by onedrive-pref.

GUI may have notifications when error occurs, but I haven't implemented GUI.

**Comment by tcass1977** [comment]
My goodness that was fast. Thank you immensely for your work.  Even without
notifications it is an amazing piece of work.  From what I hear, Microsoft
it going to release the API's because they want to spread their software if
they can not take the market.  I hope you did good on your exams.  I know a
little too late for accolades, but you deserve credit.  I will be willing
to host ppa or what I can when you go solid with it.  Keep me in your
contacts.

AllliedBass

**Comment by xybu** [comment]
I am glad you like it :)

This project gets me relaxed from tense coursework (you know what... tons of stuff due in the next couple days... dark days before spring break)... Sometimes I can practice what I learned. Either way it is enjoyable.
