### ISSUE TITLE
OLDER & NEWER file

### ISSUE THREAD

**Issue by dmaglio** [xybu/onedrive-d-old#122]
When sync my folder, it's full of duplicated file with suffix OLDER or NEWER..
I still waiting the daemon ;)

**Comment by xybu** [comment]
I wish I had a switch to prevent those versions abandoned for long from running. Why are they still in circulation?

The problem you mentioned has been solved for long in 1.0-dev branch (marked deprecated last week). We are now at "future" branch which greatly improves the program's stability and "future-daemon" branch which daemonizes the code in "future" branch. Both are under testing but the overall feedback seems good. You could checkout "future" branch and see how things work.

Sent from my Windows Phone

**Comment by Dutchglory** [comment]
Maybe just delete the old branch and only work with new "future" branch...  and users should UPDATE!!! 🔧

**Comment by dmaglio** [comment]
i have deleted old onedrive-d e reinstalled the new as descripted...
