### ISSUE TITLE
Possible problem with PIP >= 6.0

### ISSUE THREAD

**Issue by Kenarso** [xybu/onedrive-d-old#123]
I use Elementary OS. First I had install pip manually.
After that  I want to install onderive-d with "install.sh" and get follow error:

Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    requirements = [str(r.req) for r in requirements]
  File "setup.py", line 14, in <listcomp>
    requirements = [str(r.req) for r in requirements]
  File "/usr/local/lib/python3.2/dist-packages/pip/req/req_file.py", line 19, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session'

I don't know what can I do.

**Comment by xybu** [comment]
duplicate #118

**Comment by Kenarso** [comment]
I done it but I get the same error

**Comment by xybu** [comment]
In `setup.py`, deleting the lines 

``` python
requirements = parse_requirements('requirements.txt')
requirements = [str(r.req) for r in requirements]
```

and changing the line

``` python
install_requires=requirements,
```

to

``` python
install_requires = ['requests', 'urllib3', 'certifi', 'send2trash'],
```

I forgot to mention the `requirement=` lines are also needed to be deleted.

**Comment by xybu** [comment]
I have made the changes in future-daemon branch. You could check it out and see how things go. If okay we can merge it with future branch.

**Comment by Kenarso** [comment]
OK, it works fine! Thx, great job!
