### ISSUE TITLE
fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by fokafoga** [xybu/onedrive-d-old#138]
The last version drops a "Complier exception" buring instalatt on openSuSE 13.1.

Installed /usr/lib/python3.3/site-packages/onedrive_d-1.1.0dev-py3.3.egg
Processing dependencies for onedrive-d==1.1.0dev
Searching for psutil==2.1.1
Reading https://pypi.python.org/simple/psutil/
Best match: psutil 2.1.1
Downloading https://pypi.python.org/packages/source/p/psutil/psutil-2.1.1.tar.gz#md5=72a6b15d589fab11f6ca245b775bc3c6
Processing psutil-2.1.1.tar.gz
Writing /tmp/easy_install-ve8z5k/psutil-2.1.1/setup.cfg
Running psutil-2.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ve8z5k/psutil-2.1.1/egg-dist-tmp-fzmkpq
warning: no previously-included files matching '*' found under directory 'docs/_build'
psutil/_psutil_linux.c:12:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by xybu** [comment]
#136

**Comment by fokafoga** [comment]
Yeeees, then python-devel package helps it! Thx.
