### ISSUE TITLE
Failed to dump config to file

### ISSUE THREAD

**Issue by sibojia** [xybu/onedrive-d-old#142]
When running onedrive-pref:

```
Please enter the abs path to sync with your OneDrive (default: /home/user/OneDrive): 
[2015-03-14 11:51:20,025] WARNING: MainThread: failed to dump config to file "/home/user/.onedrive/config_v2.json".
Path successfully set.
```

And therefore onedrive-d can't start as it can't find config file.
However onedrive-pref can create "~/.onedrive/ignore_v2.ini", so the permission should be OK.

Thanks!

**Comment by xybu** [comment]
The file `~/.onedrive/ignore_v2.ini` is copied by the install.sh script at installation time, not by program.
Make sure your $USER have RWX permission on path `~/.onedrive`. It felt like it was created by root, not $USER.

**Comment by sibojia** [comment]
Solved. I should have followed your installation guide. Thanks!

**Comment by mlstein** [comment]
Thanks! This works right away! I was so used to sudoing everything...
