### ISSUE TITLE
Problem for starting onedrive-pred and onedrive-d on raspbian

### ISSUE THREAD

**Issue by yann120** [xybu/onedrive-d-old#145]
Hi, I have just installed the last version of onedrive-d on my rasoberry but I have an error when I start onedrive-pref or onedrive-d : I have an error : CRITICAL : MainThread: onedrive-d may not be installed properly. Exit. 
I think that I have done everything what it is written in the readme.
Thanks a lot,
Yann

**Comment by xybu** [comment]
Di you run onedrive-pref to set up the program?

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by yann120** [comment]
yes but when I start onedrive-pref I have the error message.
Thanks :)

**Comment by xybu** [comment]
It means the path `~/.onedrive` with that is supposed to be there does not exist. Check README.md installation step 4.

**Comment by yann120** [comment]
I understand my error : I didn't right the point before "onedrive" and that change everything! :) 
It works great now! 
Thanks for your amazing work xybu! You are the best :D

**Comment by wlorin** [comment]
Hi,

I installed onedrive-d on debian and have this exact same issue. I used the install.sh to set it up and the folder ~/.onedrive does exist (and contains a ignore_v2.ini file). I'm running onedrive-d as root.

I don't get how the TE solved his issue - any hints?

**Comment by vk5ztv** [comment]
I think you have to run onedrive-d as the user in whose home directory ~/.onedrive exists. If you run it as root it should be looking for for /root/.onedrive, not ~/.onedrive. At least, that is my understanding (the dev may correct me).
