### ISSUE TITLE
Possible bug when moving files to local repo

### ISSUE THREAD

**Issue by xybu** [xybu/onedrive-d-old#19]
Currently MOVED_TO is paired with MOVED_FROM. If one moves files from any dir other than local repo to local repo, the monitor will go wrong.

Possible fixes (with #8):
Treat MOVED_TO as file modification events where the file needs to be uploaded.
Treat MOVED_FROM events as file deletions.

Future enhancement:
Use MOVED_FROM buffer to delay file deletions. If M_T matches items in the buffer, issue mv command; otherwise handle the event normally.

When moving a file,  the file content, size, and mtime don't change. Thus they can be used to hash a file in the buffer.

**Comment by starrwang** [comment]
Hi, may this humble suggestion work? 
read as much lines as possible from inotify pipe (however there shoud be a limit number or timeout etc), insert into a dict if we meet a MOVED_FROM record, query the dict if we meet a MOVED_TO record; the we can pair them to form a mv task; in other cases, just put it into a temp task list; after we are done with this bunch of parsing, queue the list into the task queue.
