### ISSUE TITLE
Bug when moving files swiftly

### ISSUE THREAD

**Issue by xybu** [xybu/onedrive-d-old#21]
Say, there is a file at /a/b/cc.c
mv /a/b/cc.c /a
mv /a/cc.c /a/b/cc.c

And daemon will say the file not found when performing synchronization.

**Comment by snacsnoc** [comment]
Do we know why this is happening?

**Comment by xybu** [comment]
I guess it is due to the delay of the worker threads. The same file gets moved and the old tasks about the file become invalid and should not run anymore. If the task is consumed, the file really doesn't exist in the specified path.

**Comment by snacsnoc** [comment]
Is this a common occurrence though? I mean, moving files _while_ performing a sync?

**Comment by xybu** [comment]
After the daemon watcher establishes (this means the local repo and remote repo are in sync), you move files swiftly and watcher adds the corresponding tasks to the queue.
cmd 1: `mv /OneDrive/b/c.txt /OneDrive/c.txt`
->Queue will have a task "delete the remote b/c.txt and upload local c.txt to remote" but this task may not get consumed by the worker immediately.
cmd 2: `mv /OneDrive/c.txt /OneDrive/b/c.txt`
->Queue will have a task "delete the remote /c.txt and upload the local b/c.txt to remote".

When the worker consumes those tasks, as long as cmd2 is done but the queued task for cmd1 is to be performed, an error will happen.
1. When cmd 2 is done, the paths of cmd1 becomes invalid and thus consuming cmd1 will give error.
2. Or when worker1 consumes cmd1 and worker 2 consumes cmd2, worker1 says the local path is invalid while worker 2 says the remote path is invalid.

**Comment by paulstelian97** [comment]
Is there any way to make sure that successive tasks on a file will be done in order? Like assigning them to the same worker. Maybe keep lists of files which each worker has tasks to work for, and then check those lists so that any subsequent tasks of the same file go to the same worker and are thus ordered? (this might be highly inefficent, afaik, but it's a workable kludge until the issue is properly solved)

**Comment by xybu** [comment]
The new task queue in `future` branch should improve. Not sure to what extent though.
