### ISSUE TITLE
Cannot Whitelist Folders using ! Syntax

### ISSUE THREAD

**Issue by Andy-H-Nguyen** [xybu/onedrive-d-old#227]
Hello everyone,

I am trying to include only my music folder, but the following blacklist settings does not work. On Ubuntu 14.04
~~~~
# Ignore everything in repository root 
/*

# Folder to not ignore
!/Media/Music
~~~~
But when I run `onedrive-d start --debug` no syncing happens? Does it not support the `!` syntax?

**Comment by Torawk** [comment]
Looking at the code the ! isn't currently supported.  I was hoping to use it too..

Comment in the ignore file:

> Notes:
>  * Currently only support patterns like "*.swp", "path/to/*.swp", "\#swp#",
>    "/path/*/*.swp", etc.
>  * No '!' negation symbol support.
>  * No '**' super matching support but single '*' is for super matching.
