### ISSUE TITLE
Starting onedrive-d ... FAILED

### ISSUE THREAD

**Issue by Honney333** [xybu/onedrive-d-old#260]
When I try to start onedrive-d it fails.

Command Lines:
_~/onedrive-d$ onedrive-d start
Loading configuration ... OK
[2022-10-22 22:06:21,877] DEBUG: MainThread: running in daemon node.
Starting onedrive-d ... FAILED
ERROR: Child exited immediately with exit code 1_

Steps followed:
https://www.avoiderrors.com/how-to-sync-microsoft-onedrive-in-linux/

Linux Distro: Linux Mint

**Comment by abraunegg** [comment]
@Honney333 
> Steps followed:
> https://www.avoiderrors.com/how-to-sync-microsoft-onedrive-in-linux/

Those instructions are rather obsolete. There are only 5 reliable ways to access OneDrive on Linux/Unix platforms:

* Via the OneDrive Client for Linux - https://github.com/abraunegg/onedrive - this 'syncs' your data, bi-directional operation, open source and free. Supports Personal, Business & SharePoint account types and Shared Folders. A Docker container is also available for all major architectures (x86_64, ARMHF, AARCH64). If you need a GUI for onedrive client management use: https://github.com/bpozdena/OneDriveGUI
* Via the 'onedriver' client - https://github.com/jstaf/onedriver - Native file system that only provides the OneDrive 'on-demand' functionality, open source and free. Supports Personal, Business account types. Currently does not support Shared Folders or SharePoint.
* Via 'rclone' - https://rclone.org/ - one way sync client, open source and free. Has limitations with SharePoint.
* Via non-free clients such as 'insync', 'ExpanDrive'
* Via the web browser of your choice
