### ISSUE TITLE
Errno 2 while trying to start daemon

### ISSUE THREAD

**Issue by Vistaus** [xybu/onedrive-d-old#36]
I'm running Arch Linux and I tried to run master and wip but they crash with Errno 2.

vistaus@yoga13:~/fromsvngit/onedrive-d$ sudo onedrive-d
Traceback (most recent call last):
  File "/usr/bin/onedrive-d", line 9, in <module>
    load_entry_point('onedrive-d==0.8', 'console_scripts', 'onedrive-d')()
  File "/usr/lib/python2.7/site-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/daemon.py", line 169, in main
    subp = subprocess.Popen(["onedrive-auth"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 709, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
vistaus@yoga13:~/fromsvngit/onedrive-d$ 

I've installed all the dependencies it needs. I also tried to run it with Python 3 but it needs to be updated for Python 3.

Why is it crashing and can I fix it somehow?

**Comment by xybu** [comment]
wip is in the progress of transforming all command-line utils to GUI ones.

'onedrive-auth' has been changed to 'onedrive-prefs' but I am not done yet.

You may run `onedrive-prefs` before running daemon to bypass the issue temporarily.

**Comment by xybu** [comment]
I pushed my new work on wip. Any help with testing is appreciated.

**Comment by Vistaus** [comment]
I also had it on the other branch, but never mind that you read over that. Anyway: updated the WIP branch (git pull), it now correctly displays the prefs tool but it still exits out because it can't find 'webkit' even though Python WebKit module is installed on my Arch Linux.

vistaus@yoga13:~/fromsvngit/onedrive-d$ onedrive-d
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/prefs.py", line 198, in open_auth_window
    self.authWindow = OneDrive_AuthWindow(api = self.liveAPI, parentWindow = self)
  File "/usr/lib/python2.7/site-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/prefs.py", line 27, in **init**
    import webkit
ImportError: No module named webkit
OneDrive-d cannot get information from the server. Exit.
vistaus@yoga13:~/fromsvngit/onedrive-d$

**Comment by xybu** [comment]
Could you try importing "webkitgtk" instead "webkit"? If neither works please help me find the name of the webkit module on your machine.
Here is a link that might help: https://www.gramps-project.org/wiki/index.php?title=GeoView#Gecko_.28_GtkMozEmbed_.29

**Comment by Vistaus** [comment]
How can I import webkitgtk? I don't see any reference in setup.py or onedrive-d executable.

**Comment by xybu** [comment]
The python binding of webkit is installed from the system package `python-webkit` or `pywebkitgtk` in `inst`. You can issue command

```
python -c "import webkitgtk"
```

to see if python can find and import the package `webkitgtk`.

For Arch this system package is required: https://www.archlinux.org/packages/extra/i686/pywebkitgtk/
but I don't know its Python binding's name.

**Comment by Vistaus** [comment]
For some reason, now it does work. Thanks :)

But it still doesn't fully work. After I've connected to OneDrive, it still says that I'm not authenticated. Even after re-opening the Prefs...
