### ISSUE TITLE
Not Syncing folder from Fedora 20

### ISSUE THREAD

**Issue by lord-lethris** [xybu/onedrive-d-old#38]
Installed fine, although I had to manually install pynotify via "yum install notify-python"
It'll sync files and folders "to" Fedora brilliantly.  However, it wont sync "folders" to OneDrive.

note the "folder_test" folder and "MINECRAFT" folder are missing.

![onedrive_linux](https://cloud.githubusercontent.com/assets/1736720/3216016/085090be-efc9-11e3-80b8-7d975b76a82a.PNG)

I also checked iOS to rule out a windows comparability issue :) - The folders are not there either.

![photo 09-06-2014 12 29 48](https://cloud.githubusercontent.com/assets/1736720/3216045/972f5c0c-efc9-11e3-8698-1e1e28994af8.png)

**Comment by lord-lethris** [comment]
Further testing -> I noticed it synced the folders after a re-boot, but not the folder content.
on a second re-boot, it did sync the content.

I tested again with a fresh folder with new content, and it took 2 reboots to sync.  
First re-boot synced the folder and the second reboot synced the content.

Hope this helps.

**Comment by xybu** [comment]
Not sure what caused the issue. Perhaps that's because of the delay of the worker threads? They don't start immediately after the watcher issues a task, but may wait for a few seconds and then sync. If you run the daemon manually on terminal, there should be some logs that we can refer to.

**Comment by Vladx71** [comment]
It seems your stuff has :skull: issues with non-US character sets which is not a big problem, but it seems after a non-US file found the sync stops

> Traceback (most recent call last):
>   File "/usr/bin/onedrive-cli", line 9, in <module>
>     load_entry_point('python-onedrive==14.06.3', 'console_scripts', 'onedrive-cli')()
>   File "/usr/lib/python2.7/site-packages/onedrive/cli_tool.py", line 310, in main
>     contents = api.get(resolve_path(optz.file), byte_range=optz.byte_range)
>   File "/usr/lib/python2.7/site-packages/onedrive/cli_tool.py", line 239, in <lambda>
>     resolve_path = ( (lambda s: id_match(s) or resolve_path_wrap(s)) \
>   File "/usr/lib/python2.7/site-packages/onedrive/cli_tool.py", line 238, in <lambda>
>     resolve_path_wrap = lambda s: api.resolve_path(s and s.replace('\', '/').strip('/'))
>   File "/usr/lib/python2.7/site-packages/onedrive/api_v5.py", line 481, in resolve_path
>     raise DoesNotExists(root_id, path[i:])
> onedrive.api_v5.DoesNotExists: (u'folder.bd9651cd9de3b3af.BD9651CD9DE3B3AF!12094', [u'Kozmosz_ Az Okosak F\u0e23\u0e16ldje - A VIDE\u0e23\x93 (HD-720p).mp4'])
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/site-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/components.py", line 121, in run
>     self.consume(task)
>   File "/usr/lib/python2.7/site-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/components.py", line 87, in consume
>     old_mtime = os.stat(t.p1).st_mtime
> OSError: [Errno 2] No such file or directory: '/home/vlad/OneDrive/Video/Kozmosz_ Az Okosak F\xc3\xb6ldje - A VIDE\xc3\x93 (HD-720p).mp4'
> 
> Thread-14: done.
> Thread-16: done.
> OneDrive API error.
> Thread-15: done.

**Comment by xybu** [comment]
#44
