### ISSUE TITLE
Cannot select local folder

### ISSUE THREAD

**Issue by psturgis** [xybu/onedrive-d-old#46]
Running Lubuntu 14.04
After entering onedrive-d i get the pop-up to choose a local folder which exists.
I cannot select however any folder. In th terminal screen this message appears:

/usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/prefs.py:296: GtkWarning: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed
  gtk.main()
/usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/prefs.py:296: Warning: /build/buildd/glib2.0-2.40.0/./gobject/gtype.c:4210: type id '0' is invalid
  gtk.main()
/usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/prefs.py:296: Warning: can't peek value table for type '<invalid>' which is not currently referenced
  gtk.main()
/usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/prefs.py:296: GtkWarning: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed
  gtk.main()
/usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/prefs.py:296: Warning: /build/buildd/glib2.0-2.40.0/./gobject/gtype.c:4210: type id '0' is invalid
  gtk.main()
/usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/prefs.py:296: Warning: can't peek value table for type '<invalid>' which is not currently referenced
  gtk.main()
OneDrive-d was not authenticated or properly configured. Exit.
Exception ImportError: 'No module named onedrive' in <bound method PersistentOneDriveAPI.__del__ of <onedrive.api_v5.PersistentOneDriveAPI object at 0xb597d7ec>> ignored

How to solve this?

**Comment by xybu** [comment]
Did you run ./inst install
to install the prerequisite packages, python-onedrive, in particular?

**Comment by psturgis** [comment]
Regarding to the log is think so.(see below)

peter@netbook:~/onedrive-d$ ./inst install
Start setting up onedrive-d package.
Detected package manager: apt-get
[sudo] password for peter: 
Pakketlijsten worden ingelezen... Klaar
Boom van vereisten wordt opgebouwd  
De status informatie wordt gelezen... Klaar
git is al de nieuwste versie.
python-dateutil is al de nieuwste versie.
inotify-tools is al de nieuwste versie.
python-pip is al de nieuwste versie.
python-webkit is al de nieuwste versie.
rcs is al de nieuwste versie.
De volgende pakketten zijn automatisch geïnstalleerd en zijn niet langer nodig:
  libunibreak1 libzlcore-data libzlcore0.12 libzltext-data libzltext0.12
  libzlui-qt4 linux-headers-3.13.0-24 linux-headers-3.13.0-24-generic
  linux-image-3.13.0-24-generic linux-image-extra-3.13.0-24-generic
  thunderbird-locale-en thunderbird-locale-en-gb thunderbird-locale-en-us
  thunderbird-locale-nl
Use 'apt-get autoremove' to remove them.
0 pakketten opgewaardeerd, 0 pakketten nieuw geïnstalleerd, 0 te verwijderen en 10 niet opgewaardeerd.
Downloading/unpacking python-onedrive from git+https://github.com/mk-fg/python-onedrive.git
  Cloning https://github.com/mk-fg/python-onedrive.git to /tmp/pip_build_root/python-onedrive
  Running setup.py (path:/tmp/pip_build_root/python-onedrive/setup.py) egg_info for package python-onedrive

Installing collected packages: python-onedrive
  Found existing installation: python-onedrive 14.06.3
    Uninstalling python-onedrive:
      Successfully uninstalled python-onedrive
  Running setup.py install for python-onedrive

```
Installing onedrive-cli script to /usr/local/bin
```

Successfully installed python-onedrive
Cleaning up...
running install
running bdist_egg
running egg_info
creating onedrive_d.egg-info
writing requirements to onedrive_d.egg-info/requires.txt
writing onedrive_d.egg-info/PKG-INFO
writing top-level names to onedrive_d.egg-info/top_level.txt
writing dependency_links to onedrive_d.egg-info/dependency_links.txt
writing entry points to onedrive_d.egg-info/entry_points.txt
writing manifest file 'onedrive_d.egg-info/SOURCES.txt'
reading manifest file 'onedrive_d.egg-info/SOURCES.txt'
writing manifest file 'onedrive_d.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-i686/egg
running install_lib
running build_py
creating build
creating build/lib.linux-i686-2.7
creating build/lib.linux-i686-2.7/onedrive_d
copying onedrive_d/**init**.py -> build/lib.linux-i686-2.7/onedrive_d
copying onedrive_d/daemon.py -> build/lib.linux-i686-2.7/onedrive_d
copying onedrive_d/config.py -> build/lib.linux-i686-2.7/onedrive_d
copying onedrive_d/components.py -> build/lib.linux-i686-2.7/onedrive_d
copying onedrive_d/prefs.py -> build/lib.linux-i686-2.7/onedrive_d
creating build/lib.linux-i686-2.7/onedrive_d/res
copying onedrive_d/res/icon_256.png -> build/lib.linux-i686-2.7/onedrive_d/res
creating build/bdist.linux-i686
creating build/bdist.linux-i686/egg
creating build/bdist.linux-i686/egg/onedrive_d
copying build/lib.linux-i686-2.7/onedrive_d/**init**.py -> build/bdist.linux-i686/egg/onedrive_d
copying build/lib.linux-i686-2.7/onedrive_d/daemon.py -> build/bdist.linux-i686/egg/onedrive_d
copying build/lib.linux-i686-2.7/onedrive_d/config.py -> build/bdist.linux-i686/egg/onedrive_d
copying build/lib.linux-i686-2.7/onedrive_d/components.py -> build/bdist.linux-i686/egg/onedrive_d
copying build/lib.linux-i686-2.7/onedrive_d/prefs.py -> build/bdist.linux-i686/egg/onedrive_d
creating build/bdist.linux-i686/egg/onedrive_d/res
copying build/lib.linux-i686-2.7/onedrive_d/res/icon_256.png -> build/bdist.linux-i686/egg/onedrive_d/res
byte-compiling build/bdist.linux-i686/egg/onedrive_d/**init**.py to **init**.pyc
byte-compiling build/bdist.linux-i686/egg/onedrive_d/daemon.py to daemon.pyc
byte-compiling build/bdist.linux-i686/egg/onedrive_d/config.py to config.pyc
byte-compiling build/bdist.linux-i686/egg/onedrive_d/components.py to components.pyc
byte-compiling build/bdist.linux-i686/egg/onedrive_d/prefs.py to prefs.pyc
creating build/bdist.linux-i686/egg/EGG-INFO
copying onedrive_d.egg-info/PKG-INFO -> build/bdist.linux-i686/egg/EGG-INFO
copying onedrive_d.egg-info/SOURCES.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying onedrive_d.egg-info/dependency_links.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying onedrive_d.egg-info/entry_points.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying onedrive_d.egg-info/requires.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying onedrive_d.egg-info/top_level.txt -> build/bdist.linux-i686/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
onedrive_d.daemon: module references **file**
creating dist
creating 'dist/onedrive_d-0.8-py2.7.egg' and adding 'build/bdist.linux-i686/egg' to it
removing 'build/bdist.linux-i686/egg' (and everything under it)
Processing onedrive_d-0.8-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg
Extracting onedrive_d-0.8-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Removing onedrive-d 0.85 from easy-install.pth file
Adding onedrive-d 0.8 to easy-install.pth file
Installing onedrive-prefs script to /usr/local/bin
Installing onedrive-d script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg
Processing dependencies for onedrive-d==0.8
Searching for python-onedrive==14.06.3
Best match: python-onedrive 14.06.3
Adding python-onedrive 14.06.3 to easy-install.pth file
Installing onedrive-cli script to /usr/local/bin

Using /usr/local/lib/python2.7/dist-packages
Searching for PyYAML==3.11
Best match: PyYAML 3.11
Processing PyYAML-3.11-py2.7-linux-i686.egg
PyYAML 3.11 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/PyYAML-3.11-py2.7-linux-i686.egg
Searching for urllib3==1.7.1
Best match: urllib3 1.7.1
urllib3 1.7.1 is already the active version in easy-install.pth

Using /usr/lib/python2.7/dist-packages
Searching for requests==2.2.1
Best match: requests 2.2.1
requests 2.2.1 is already the active version in easy-install.pth

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for onedrive-d==0.8
Setup is done. You can run onedrive-d command after finishing the settings.
peter@netbook:~/onedrive-d$ /usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/prefs.py:296: GtkWarning: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed
  gtk.main()
/usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/prefs.py:296: Warning: /build/buildd/glib2.0-2.40.0/./gobject/gtype.c:4210: type id '0' is invalid
  gtk.main()
/usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/prefs.py:296: Warning: can't peek value table for type '<invalid>' which is not currently referenced
  gtk.main()

**Comment by psturgis** [comment]
Hello,

I did respond to your mail but didn hear since. Could you inform me 
about the status.
Peter
op 05-07-14 15:09, Xiangyu Bu schreef:

**Comment by xybu** [comment]
From your previous log, there seems to be issues with the Gtk binding package on Lubuntu (LXDE). Honestly I have no idea how to solve it. 

The current GUI library, PyGtk is too old and I plan to replace it with PyGObject (the successor) or even switch to wxPython which seems cross-platform. But again, I don't know if this move would solve the problem.
