### ISSUE TITLE
onedrive-d freezes; requires relogin on each launch

### ISSUE THREAD

**Issue by robinhood2014** [xybu/onedrive-d-old#47]
Every time I launch onedrive-d from the terminal, it will work for a while but then freeze after a number of files. Once it hasn't done anything for a number of minutes, I can only press Control-C to kill the process, and then it returns something like this:

Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 9, in <module>
    load_entry_point('onedrive-d==0.8', 'console_scripts', 'onedrive-d')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/daemon.py", line 190, in main
    OneDrive_StatusIcon(API).run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.8-py2.7.egg/onedrive_d/daemon.py", line 145, in run
    gtk.main()
KeyboardInterrupt

Then, when I re-launch onedrive-d, it requires that I re-login to my Microsoft account.

What's the deal?

**Comment by xybu** [comment]
May I know your OS and desktop environment?

Sincerely,Xiangyu Bu

Date: Sat, 5 Jul 2014 19:14:48 -0700

**Comment by robinhood2014** [comment]
I use Ubuntu. I tend to go between Unity and LXDE (Lubuntu).

--- Original Message ---

**Comment by xybu** [comment]
Did the cloud icon show in the status bar at all? It sounded like gtk didn't initialize the stuff, and the OneDrive user credentials couldn't be saved.
How well are `onedrive-cli` and `onedrive-prefs` going?

**Comment by robinhood2014** [comment]
I never tried looking at those processes.

--- Original Message ---

**Comment by beldin68** [comment]
I have the same issue on Ubuntu 14.04.  I get to Thread-4  and everything stops - it stops at the same point every time.  Thread-4.

Here is the output after I ctrl+c to stop.  It is syncing 246MB out of ~9GB that is in my OneDrive.

---

^CTraceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 9, in <module>
    load_entry_point('onedrive-d==0.85', 'console_scripts', 'onedrive-d')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/daemon.py", line 192, in main
    OneDrive_StatusIcon(API).run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/daemon.py", line 147, in run
    gtk.main()
KeyboardInterrupt

---

onedrive-prefs works as expected - and I am not exactly sure what to expect from onedrive-cli (the options that show up are not familiar to me and I won't use them as a result....)

One other thing - the files that have synced show a LOCK on them in Nautilus.

**Comment by xybu** [comment]
If the files have a lock icon shown in Nautilus, then the file owner may be set wrong.

A possibility may be that, since OneDrive has some limits that restrict you from uploading / downloading too much data, or querying things to frequently, the client program cannot work further after blocked by the OneDrive server. Given what you store in OneDrive, may this occur?

When debugging, it is appreciated if you could share some valuable log after `onedrive-d` is run and before Ctrl+C is hit.
