### ISSUE TITLE
Cannot select folder on setup

### ISSUE THREAD

**Issue by baddwin** [xybu/onedrive-d-old#49]
When I select sync folder on setup, the window disappears. I use Kubuntu Trusty.  
here is the error log:

```
usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/prefs.py:296: GtkWarning: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed
  gtk.main()
/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/prefs.py:296: Warning: /build/buildd/glib2.0-2.40.0/./gobject/gtype.c:4210: type id '0' is invalid
  gtk.main()
/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/prefs.py:296: Warning: can't peek value table for type '<invalid>' which is not currently referenced
  gtk.main()
```

**Comment by achomitz** [comment]
Ubuntu 14.04 64-bit: got the same error:
/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/prefs.py:296: GtkWarning: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed
  gtk.main()
/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/prefs.py:296: Warning: /build/buildd/glib2.0-2.40.0/./gobject/gtype.c:4210: type id '0' is invalid
  gtk.main()
/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/prefs.py:296: Warning: can't peek value table for type '<invalid>' which is not currently referenced
  gtk.main()
Speicherzugriffsfehler (Speicherabzug geschrieben)

Is ithere a solution? Thank You.

**Comment by xybu** [comment]
Looks like PyGTK is buggy on many platforms.
The next version will not use PyGTK anymore.
