### ISSUE TITLE
Cannot sync files nested more than 2 levels 

### ISSUE THREAD

**Issue by ImagingPro** [xybu/onedrive-d-old#53]
I am unable to retrieve/sync anything that is contained in folders nested more than two levels.

Examples:
onedrive/folder1/folder2/\* = all files and folders are synced correctly
onedrive/folder1/folder2/folder3/... = folders are synced correctly but only files contained into folder1 are synced

Folders are scanned by onedrive-d but nothing is downloaded. I tested different folder structures and I can reproduce this. 

I run Mint 17 Cinnamon 64bit and the local Onedrive folder is on ext4 partition, but it is the same with a NTFS partition.

**Comment by xybu** [comment]
My personal OneDrive has dirs nested in at least 4 levels and I haven't noticed this failure. Could you give me more information, more specifically,
1. Is the "folder3" created correctly?
2. Can you download the file via 'onedrive-cli' command?
3. Could you run 'onedrive-d' manually and copy it's debug log here?

Thanks!

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by ImagingPro** [comment]
Hi Xiangyu,

thanks for the quick reply. Yeah, it really is a strange issue.

As for your questions:
1) Yes, all folders below folder 2 are created correctly, they are just empty. I tried leaving onedrive-d running all night to see if it was just a delay, but nothing changed.

2) I tried playing with onedrive-cli but I couldn't really figure out how to do it. I will try again today.

3) That I can do, I will send you a follow up as soon as possible (I am on Windows now).

And thank you for the great job, Onedrive-d is awesome (I am sure there's a way to get it to work for me too)

Andrea

Andrea Galli, PhD.

Copenhagen Hepatitis C Program

Department of Infectious Diseases and Clinical Research
Centre 144/136
Hvidovre Hospital, University of Copenhagen
Kettegård Allé 30

2650 Hvidovre

Denmark

Phone: +45 38626054

Fax: +45 38623797

Date: Wed, 23 Jul 2014 05:17:07 -0700

**Comment by xybu** [comment]
If you run `onedrive-cli`, it will tell you its command-line arguments. You may try downloading a file or uploading one and see if they can succeed. If I remember correctly, they are `onedrive-cli get REMOTE_FILE_PATH` and `onedrive-cli put LOCAL_FILE_NAME` (upload to OneDrive root).

**Comment by ImagingPro** [comment]
Hi Xiangyu,

sorry for the late reply, I did some more tests and it looks like every time I close the program and reopen it, more files get synched, but if I leave it running nothing happens.

To answer your original questions:
2. Yes I can and I can save it in the correct place (so it is not a permission issue)
3. I attach the log of a whole session, after that onedrive-d did not do anything else

As a side, when I was trying with onedrive-cli I received a lot of errors about requests being too close to each other and having to wait a certain number of seconds (op to a few minutes in cases). I wonder if that can be part of the problem.

By the way, I am using the wip branch of onedrive-d.

Thank you for you help,

Andrea

Date: Wed, 23 Jul 2014 05:17:07 -0700

**Comment by g33k247** [comment]
I'm seeing the same exact issues described in this thread. onedrive-d creates folders multiple levels deep, but no syncing occurs deeper than the second level. Also, each time I run onedrive-d a few more files sync, but there's no discernible pattern why it's syncing some files and not others.

**Comment by xybu** [comment]
Could you try and see if 1.0-dev still has such problem? Since my own OneDrive, with indeed a complex hierarchy, gets synced fine, I have no idea how to reproduce the issue. I really appreciate it if more details and the program output can be provided for diagnosis.

**Comment by ricontre** [comment]
Hi Xiangyu,

I am a newbie on linux and onedrive-d. I downloaded 1.0-dev and run it on my machine, and I am experiencing very similar issue (if not the same) as described above. All folder structure is synched OK, but file synch goes up to 2-3 levels down, and then folders are empty.

I have ~4-5Gb in OneDrive, and it seems that onedrive-d finds issues that prevents it from a full sync every time I run it. Below is the last part of the output in my last attempt. Any ideas of what might be going on?

Thanks,
Ignacio

---

[2014-12-29T03:45:05-0800] syncer   INFO: syncing /home/ubuntu/OneDrive/Documents/MBA/Cursos/MBA290V - Telecom and Media/07 - TiVO/
[2014-12-29T03:45:06-0800] syncer   INFO: syncing /home/ubuntu/OneDrive/Documents/MBA/Cursos/MBA290V - Telecom and Media/08 - Akamai/
[2014-12-29T03:45:07-0800] syncer   INFO: syncing /home/ubuntu/OneDrive/Documents/MBA/Cursos/MBA290V - Telecom and Media/09/
[2014-12-29T03:45:09-0800] syncer   INFO: syncing /home/ubuntu/OneDrive/Documents/MBA/Cursos/MBA290V - Telecom and Media/10/
[2014-12-29T03:45:10-0800] syncer   INFO: syncing /home/ubuntu/OneDrive/Documents/MBA/Cursos/MBA290V - Telecom and Media/11/
[2014-12-29T03:45:12-0800] syncer   INFO: syncing /home/ubuntu/OneDrive/Documents/MBA/Cursos/MBA290V - Telecom and Media/12/
Exception in thread syncer:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/onedrive_d-1.0_dev-py3.4.egg/onedrive_d/daemon.py", line 695, in run
    self.merge_dir(entry)
  File "/usr/local/lib/python3.4/dist-packages/onedrive_d-1.0_dev-py3.4.egg/onedrive_d/daemon.py", line 535, in merge_dir
    all_remote_items = self.api.list_entries(remote_path)
  File "/usr/local/lib/python3.4/dist-packages/onedrive_d-1.0_dev-py3.4.egg/onedrive_d/live_api.py", line 197, in list_entries
    return self.parse_response(r, ProtocolError)['data']
  File "/usr/local/lib/python3.4/dist-packages/onedrive_d-1.0_dev-py3.4.egg/onedrive_d/live_api.py", line 67, in parse_response
    raise error(ret)
live_api.ProtocolError: 'server_internal_error: An unexpected processing error occurred. Please contact Microsoft.'

**Comment by paulstelian97** [comment]
As of what I've read of this thread:
1) Don't have too many requests at once, as they will fail.
2) Apparently, the list of files should be available and if a file errs out, it should be placed to the back of the queue so that the daemon will eventually try to fetch it again. Also, parse any errors from the server (like "too many requests" kind of errors) as you can make them worse if you just ignore them.

**Comment by xybu** [comment]
Basically the OneDrive server has many limits. Wish the new API implementation in `future` branch (ver > 1.0) can solve the problems for you.
