### ISSUE TITLE
inotifywait not exiting after program exit

### ISSUE THREAD

**Issue by pvibert** [xybu/onedrive-d-old#54]
Perhaps this is by design, but whenever I close onedrive-d (either via Ctrl-C or right click on statubar icon -> Exit), it leaves the spawned inotifywait running. If the program is launched and closed several times, the same number of inotifywaits keep running. Running Ubuntu 14.04.

**Comment by xybu** [comment]
Not sure which version you are mentioning, but the problem in 1.0-dev wasn't noticed. May you try out this version?
