### ISSUE TITLE
onedrive-cli fails on ubuntu 14.04

### ISSUE THREAD

**Issue by DGPickett** [xybu/onedrive-d-old#56]
dgp@dgp-p6803w:~$ onedrive-cli tree
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==14.08.0', 'console_scripts', 'onedrive-cli')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 236, in main
    api = api_v5.PersistentOneDriveAPI.from_conf(optz.config)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/conf.py", line 46, in from_conf
    with open(path, 'rb') as src:
IOError: [Errno 2] No such file or directory: '/home/dgp/.lcrc'
dgp@dgp-p6803w:~$ find . -name .lcrc -ls
find: `./.config/menus': Permission denied
dgp@dgp-p6803w:~$

**Comment by DGPickett** [comment]
PS: I see files renamed "file_name (OLDER_<unix_time.fraction>)" or (NEWER_*) in my home dir, including:

-rw-------  1 root root      1449 Aug 13 09:12 .lcrc (NEWER_1407935571.48)
-rw-------  1 dgp  dgp       1449 Aug 13 10:16 .lcrc (NEWER_1407939418.0)

Anyone know what is renaming and why?  Is one_drive-d fighting with itself?

**Comment by xybu** [comment]
The version you used didn't have a database to determine which file is newer and which is older, so one of the conflicting pairs will be renamed with its time stamp. The next version will have a database and there will be much less renaming.

And please don't sync your ~ dir with OneDrive. The former has many hidden files and contains the config files of onedrive-d. Please use a separate, clean dir.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by DGPickett** [comment]
Perhaps onedrive-d can learn to avoid, or apply special processes, to his own files.  

How do I turn off the ~ target?  

Sometimes there are files we want backed up in .name dirs.  

If I make a dir to configure to this cloud, can I sym-link dirs in there?

Stuff in OneDrive sees to come loose from the hierarchical view.  What do I do about the old files not in the new set?

I would expect the newest to remain un-re-named.

As most ISPs give more download than upload bw, downloading files for comparison is a better deal than gratuitous updating.  Too bad you cannot get MS to send you the file cksum or the like.

I wonder if it will keep going now.  Well, back to wondering what to do about renamed with added " (...ER_#############.##)" files.  Lucky me, most are unique now, except .lcrc of course.

**Comment by xybu** [comment]
Hopefully the ignore list (exclusion list) can help with ignoring files you don't want. The one in 0.85 is too rigid to be useful. The one in 1.0.0-dev works like .gitignore.

Also in 1.0.0-dev a sqlite db is created to store the last snapshot of the OneDrive file hierarchy when the daemon runs. Therefore it can judge which files are strictly newer or older. But for safety when the "absoluteness" isn't deterministic there is still renaming.

The program doesn't distinguish symlinks so your idea would work.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by DGPickett** [comment]
OK, it honors sym links to dirs as dirs.  I thought so.  Google Drive is not so nice with MS links, but InSync does, too!

A db of file paths and mod dates is probably OK, esp. if date granularity is to the second or less.  Size is helpful occasionally, but something like cksum is far better.  Maybe next gen clouds will have standard cksum of MD5.

The exclude list might intrinsically include .lcrc ?

Is renaming really necessary?  One file should survive with the original name in any case, perhaps hard linked to a long name if that is important and to make it survive if the barefoot name is removed.

**Comment by DGPickett** [comment]
Even though I moved the target dirextory, it keeps updating ~/.lcrc

Do I need to wipe files/dirs during restart?

Output:
onedrive.api_v5.DoesNotExists: (u'me/skydrive', [u'.dropbox', u'instance1'])
local_mon: received a task: ['/home/dgp/', 'CLOSE_WRITE,CLOSE', '.lcrc']
Thread-2: executed task: Task(put, /home/dgp/.dropbox/instance1/PENDING_5f_qF_, /.dropbox/instance1/)
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==14.08.0', 'console_scripts', 'onedrive-cli')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 323, in main
    resolve_path(optz.folder), overwrite=not optz.no_overwrite)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 392, in put
    data=src, method='put', auth_header=True)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 329, in **call**
    return self.request(api_url(), *_kwz)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 176, in request
    raise raise_for.get(code, ProtocolError)(code, message)
onedrive.api_v5.ProtocolError: (420, {u'message': u"The request wasn't made because the same type of request was repeated too many times. Wait 241 seconds and try again.", u'code': u'request_throttled'})
local_mon: received a task: ['/home/dgp/', 'CLOSE_WRITE,CLOSE', '.lcrc']
Thread-1: executed task: Task(put, /home/dgp/.lcrc, /)
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==14.08.0', 'console_scripts', 'onedrive-cli')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 323, in main
    resolve_path(optz.folder), overwrite=not optz.no_overwrite)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 392, in put
    data=src, method='put', auth_header=True)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 329, in **call**
    return self.request(api_url(), *_kwz)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 176, in request
    raise raise_for.get(code, ProtocolError)(code, message)
onedrive.api_v5.ProtocolError: (420, {u'message': u"The request wasn't made because the same type of request was repeated too many times. Wait 329 seconds and try again.", u'code': u'request_throttled'})
local_mon: received a task: ['/home/dgp/', 'CLOSE_WRITE,CLOSE', '.lcrc']
Thread-1: executed task: Task(put, /home/dgp/.lcrc, /)

**Comment by xybu** [comment]
.lcrc is the file to store access tokens by python-onedrive package. The token expires after some interval and the file will store a new token. I guess this is the reason why that file gets updated.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by DGPickett** [comment]
Well, I have been busy cleaning up the mess of files created and renamed, uploaded, downloaded.  Soon I will try again for a clean start.

**Comment by DGPickett** [comment]
If you move ~/.lcrc to ~/.onedrive/, we could ignore it more easily, and it would be labeled.

**Comment by DGPickett** [comment]
I made the mistake of running it under root, restarting it, and so got my files displaced by root ones with different permissions, but I renamed the originals back now and restarted under my id.  

Some of the renames are irregular: 'Untitled spreadsheet.gdsheet (OLDER_1403887005.gdsheet'

Some stacked 'name (OLDER__._) (OLDER__._)'

**Comment by DGPickett** [comment]
Loss off date modified stamp is a big bummer for me.

**Comment by DGPickett** [comment]
Is it stuck in rejection for too short a wait?

$ tail -22f onedrive.log
    self.listdir(root_id)))[name]
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 497, in listdir
    offset=offset)['data']
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 346, in listdir
    return self(ujoin(folder_id, 'files'), dict(limit=limit, offset=offset))
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 329, in **call**
    return self.request(api_url(), *_kwz)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 176, in request
    raise raise_for.get(code, ProtocolError)(code, message)
onedrive.api_v5.ProtocolError: (420, {u'message': u"The request wasn't made because the same type of request was repeated too many times. Wait 420 seconds and try again.", u'code': u'request_throttled'})
Exception in thread Thread-185:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 300, in run
    print API('me/skydrive/recent_docs')['data']
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 338, in __call**
    return self.request(api_url(), *_request_kwz)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 176, in request
    raise raise_for.get(code, ProtocolError)(code, message)
ProtocolError: (420, {u'message': u"The request wasn't made because the same type of request was repeated too many times. Wait 71 seconds and try again.", u'code': u'request_throttled'})

**Comment by DGPickett** [comment]
It seems like that last report was transient.  A daemon should have a well structured log, in a dedicated dir and moving to new files periodically.  Indications of failure like this should trigger some subsequent indication of success if it is not terminal.

**Comment by DGPickett** [comment]
No recent files showing up.  I'd say onedrive-d is a start, but way crude compared to InSync on Google Drive.  Is there hope in the future of accurate file dating, no file renaming, except perhaps in delete processing, and delete/rename/move processing?

There is virtue in having a cloud that only does logical deletes and overwrites, i.e., keeps all versions in some form, maybe moving them to a shadow tree.
