### ISSUE TITLE
Creates "Older" versions of files recursivly

### ISSUE THREAD

**Issue by ghost** [xybu/onedrive-d-old#58]
![screenshot from 2014-08-17 12 03 18](https://cloud.githubusercontent.com/assets/8470383/3944265/45c24ccc-25f6-11e4-898b-d882578dd292.png)

When opening a file, edit it and close it, sometimes creates older versions of it. See attached picture
OS: Ubuntu 14.04

**Comment by xybu** [comment]
#64
