### ISSUE TITLE
Setting not accessible under Mint 17 Cinnamon

### ISSUE THREAD

**Issue by ghost** [xybu/onedrive-d-old#59]
Right clicking the icon has a 'settings' button (just above 'exit'), but this does nothing.  Tried WIP branch too, same issue.

**Comment by ghost** [comment]
The exit button is similarly ineffective.  I believe a non-functional onedrive-cli process is spawned in both cases.

**Comment by reynoldsbd3** [comment]
Same issue with the settings button on Arch, but the exit button does work.

**Comment by xybu** [comment]
In 0.85 most menuitems are just placeholders. The exit button, however, is linked with the exit function (but it needs to wait for the work at hand to finish before exitting).

**Comment by Dutchglory** [comment]
right now i'm getting  <i>"This setup script does not support your distro linuxmint"</i> 

Solution: 
add linuxmint to setup.sh 

<code> 
case $DISTRIB_ID in
    debian|ubuntu|linuxmint)
</code> 

additional: The "Send2Trash" link for installation also need to be checked...

**Comment by xybu** [comment]
67704f5313b2a6c390697bba686a28ae4476d6a7
