### ISSUE TITLE
Getting /setup.sh: line 58: skydrive-cli: command not found on Kubuntu 13.10

### ISSUE THREAD

**Issue by MartinixH** [xybu/onedrive-d-old#6]
When running installation I get this error after I say yes authenticate client now. Any ideas? Thank you

**Comment by xybu** [comment]
Hi,

This means the Python client was not installed to the OS. Does the script inst_pre_requisites.sh run correctly?

**Comment by MartinixH** [comment]
Hi,
I overlooked it. git was not installed on my system so python was not installed. After that I installed git and run script again and it works. Thanks
