### ISSUE TITLE
Notifies many updates when nothing has changed

### ISSUE THREAD

**Issue by ghost** [xybu/onedrive-d-old#60]
WIP branch and release both notify numerous updates, but nothing has changed in the files concerned on the client of in the cloud, not even the accessed dates.  Not certain if upload/download is also taking place wasting bandwidth.

**Comment by ghost** [comment]
Further to this, it IS wasting bandwidth.  I have ceased to use onedrive-d.

**Comment by xybu** [comment]
There will be a switch to turn on/off notification messages in 1.0.0-dev.

And may I know what you mean by "waste bandwith"? The internet connection is used for not only downloading / uploading, but also authenticating and fetching file list.

**Comment by xybu** [comment]
I plan to drop toast notifications in favor of syncing/synced icons just like the Windows program.
