### ISSUE TITLE
Fedora 20: service script not working

### ISSUE THREAD

**Issue by Hades32** [xybu/onedrive-d-old#62]
The service script seems not to work on Fedora:

[hades32@acer onedrive-d]$ sudo service onedrive-d start
[sudo] password for hades32: 
/etc/init.d/onedrive-d: line 26: log_daemon_msg: command not found
/etc/init.d/onedrive-d: line 27: start-stop-daemon: command not found
/etc/init.d/onedrive-d: line 28: log_end_msg: command not found

**Comment by Hades32** [comment]
This might be an option: http://software.clapper.org/daemonize/

There are packages in the Fedora repo.

**Comment by xybu** [comment]
The service script needs `start-stop-daemon` which seems unavailable on Fedora.

Will check the following options:
https://github.com/serverdensity/python-daemon
https://github.com/bmc/daemonize

**Comment by xybu** [comment]
`future-daemon` branch aims to daemonize the program.
