### ISSUE TITLE
Reinstall makes the app not working

### ISSUE THREAD

**Issue by baddwin** [xybu/onedrive-d-old#66]
I installed it successfully and run it with no problem. My previous issue was resolved when I used gnome desktop (the problem is KDE's GTK theme, I guessed). Then I managed to connect with my account. But my files were in the NTFS partition, and in the console it displayed many error logs such as "untouched file blablabla..", and also many of my files were renamed with "NEWER-xxxx".

So, I have decided to create a new onedrive account and I wanted to sync my files that are in my ubuntu home partition. Then I reinstalled onedrive-d, but this time I've got problems.

Firstly, I remove the installation with command: `./setup.sh remove`  
Then it asked me more than once to confirm deletion of something packages. I answered `y` respectively.

After that, I tried to install it again with command `./setup.sh inst` and it successfully installed, I think. But when I ran command `onedrive-prefs` it displayed errors such as:

```
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-prefs", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: onedrive-d==0.85
```

I got the same when running `onedrive-cli` command.

So, I uninstalled it again, but I was asked only once, not like the first uninstall:

```
Uninstalling onedrive-d:
  /usr/local/lib/python3.4/dist-packages/onedrive_d-1.0_dev-py3.4.egg
Proceed (y/n)? y
  Successfully uninstalled onedrive-d

onedrive_d has been removed from the system.
All operations finished.
```

**Comment by xybu** [comment]
Since 1.0-dev moved to Python3, you need to uninstall the old one with the Python2 PIP manually
`pip uninstall onedrive-d` instead of `pip3 something`.
(Or maybe I should add an "upgrade" option)

**Comment by baddwin** [comment]
still, I don't get it. I ran `pip uninstall onedrive-d` but nothing happened, except blank lines.
`pip list` showed no onedrive-d package

**Comment by baddwin** [comment]
I've just reinstall previous version of onedrive-d, fortunately it is still in the trash bin... it seems okay, so I'll use it for now
