### ISSUE TITLE
Synch not working properly

### ISSUE THREAD

**Issue by charlesbloggs** [xybu/onedrive-d-old#68]
I am using onedrve-d on Linux Mint 17 and onedrive on win7. If I update a file from Linux the change
is correctly shown via onedrive on the windows machine. If however I update a file from windows
the change does not appear in the OneDrive Linux folder. As a newbie I'm sure this is probably me.
It seems to me that onedrive-d is not polling for updates. Perhaps  somebody can help ?

**Comment by xybu** [comment]
I assume you are using 0.85. This version does not pull stuff from the server after initialization, and there is no good API to do this conveniently. The version 1.0-dev solved this.

**Comment by charlesbloggs** [comment]
Thanks for your quick response. Is ver 1.0-dev functional and available ? If so, how do I update ? I see
a number of comments indicating problems with this version.

**Comment by xybu** [comment]
It is available in branch 1.0-dev, but not quite functional. The strategy is still conservative enough so none of your data will get lost. You may try it out and see its state.

By the way, if you are using Windows and Linux simultaneously, you can use BitTorrent Sync to sync your Windows OneDrive repo with the Linux OneDrive repo, of which the only thing to take care is the NTFS file namespace.
