### ISSUE TITLE
setup.sh remove unclear error message

### ISSUE THREAD

**Issue by ghost** [xybu/onedrive-d-old#69]
I had installed 1.0 because I was confused about it's status, and the install failed as in issue #65.
I tried uninstalling it using the remove script, but I have no idea if it worked or not because it says that it cannot uninstall onedrive-d as it's not installed, yet it goes on to say that onedrive_d was uninstalled.

So was it just not installed in the first place or is it still partially installed?

```
graham@Epsilon:~$ /home/graham/Desktop/onedrive-d-1.0-dev/setup.sh remove
sudo: pip: command not found
Cannot uninstall requirement onedrive-d, not installed
Storing debug log for failure in /home/graham/.pip/pip.log

onedrive_d has been removed from the system.
All operations finished.
```

**Comment by xybu** [comment]
If you check the code about `setup.sh remove`, it actually tries to delete the old, Python2k onedrive-d (version 0.85 or earlier), and then tries to delete the new, Python3k onedrive-d. So it looks like the program has been fully removed from the system.

**Comment by ghost** [comment]
Ah I see. The Uninstaller doesn't properly explain this, but that's a side affect of the currently incomplete code. I'm just going to close this report as the problem will be resolved irregardless.
