### ISSUE TITLE
I cant install on elementary OS

### ISSUE THREAD

**Issue by wolf-alexz** [xybu/onedrive-d-old#71]
Hello everyone,
Do anyone mind explain me why it doesn't work? After cloning from the git and install I get this error:

xxxxx@xxxxx-eleOS:~$ cd onedrive-d
xxxxx@xxxxx-eleOS:~/onedrive-d$ ./setup.sh inst
This setup script does not support your distro "elementary os".

Am I wrong somewhere or it's really impossible to install on elementary os (Luna).
Sorry for my english.
Thanks in advance.

**Comment by xybu** [comment]
Elementary OS is a descendant of Ubuntu, so there shouldn't be differences in package manager and package names. As a workaround, you may add "elementary os" to `setup.sh` just like the bottom of #59 did to add "linuxmint".

**Comment by wolf-alexz** [comment]
Ahh thank you it works! Sorry I didn't read completly the other posts
