### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by roman3017** [xybu/onedrive-d-old#78]
It would be nice if you could write to readme that temporarily one should configure with:

chmod +x onedrive_d/pref.py
./onedrive_d/pref.py --no-gui

and run with:

chmod +x onedrive_d/main.py
./onedrive_d/main.py

That may save some time and frustration.

**Comment by xybu** [comment]
Sorry for the frustration. I added the commands explicitly in setup script just in case the attributes get lost when the files are cloned to local fs.
a488b25dc0726e150fc2b1bb599df375031f63c0
