### ISSUE TITLE
Sync removed files properly

### ISSUE THREAD

**Issue by kpj** [xybu/onedrive-d-old#79]
I've noticed that files, which are deleted locally while onedrive-d is not running, will be downloaded as soon as onedrive-d is started again.
Is this intended behaviour or should there be some more timestamp checking?

**Comment by xybu** [comment]
We have three things known in this scenario:
1. the remote file record
2. the old file record in db
3. the fact that the file does not exist locally.

We can't guarantee that the file deleted locally is an immediate descendant of the remote file and thus it is unsafe to simply delete it remotely. For example, you may delete that file in Linux when onedrive-d is off, but later modified that file on a Windows machine.

To solve the issue more information is needed like the file hashtag and such.

**Comment by kpj** [comment]
That makes sense! In this case, keeping files is better then deleting them :-)
