### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by mariecp** [xybu/onedrive-d-old#86]
![screenshot_error](https://cloud.githubusercontent.com/assets/9453572/4835227/553bda62-5fb5-11e4-8673-65c8e3b72566.png)

How do I fix this? This happens when I install the program, as well as when I run onedrive-d

**Comment by xybu** [comment]
#65

**Comment by mariecp** [comment]
I'm a bit confused as to what to do next. I setup the configuation files.
Where do I find the live_api file?

Marie-Charlotte Pierre
Computer Science
Clemson University '17
mariecp@g.clemson.edu

**Comment by xybu** [comment]
Run ./onedrive_d/main.py

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by mariecp** [comment]
I get an import error: No module send2trash

Marie-Charlotte Pierre
Computer Science
Clemson University '17
mariecp@g.clemson.edu

**Comment by xybu** [comment]
Did you run ./setup.sh inst before setting up configuration files?

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by xybu** [comment]
If you are still interested in onedrive-d, in `future` branch (1.1?) there is a guide how to _install_ the program manually in README.md.
