### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by yorickdewid** [xybu/onedrive-d-old#87]
While I was debugging (https://github.com/xybu/onedrive-d/issues/83) I noticed Microsoft can fails as well. It looks like the skydrive server send back a 500: **server_internal_error: An unexpected processing error occurred. Please contact Microsoft.** Although the program continues, I'm not sure if raising an error is the right way to coop with server side errors.

**Comment by xybu** [comment]
Let's summarize the problem in #88. If possible could you describe what the program was doing (what changes might you make, etc. not sure) when the error occurred?
