### ISSUE TITLE
Ubuntu 12.04LTS Installation

### ISSUE THREAD

**Issue by jingoman** [xybu/onedrive-d-old#89]
Just tried to install the most current version. When I run "sudo ./setup.sh", it errors with:

E: Unable to locate package python3-pip

It seems this package isn't available. There are instructions to setup python3-pip differently for this distro version, but I was unable to get it to install. I think its because of the INSTALL_CMD variable in the setup.sh script.

Can someone provide a step-by-step guide for how to install this on my system please?

**Comment by xybu** [comment]
pip will be shipped with Python 3.4 by default. See https://docs.python.org/3/whatsnew/3.4.html#whatsnew-pep-453.

A manual installation guide of pip is available at https://pip.pypa.io/en/latest/installing.html.

**Comment by beornmorder** [comment]
Python package management is stupid. I will I could do this all with apt - it's just another thing I have to manage.
