### ISSUE TITLE
Cannot do authentication with another domain

### ISSUE THREAD

**Issue by awilkins** [xybu/onedrive-d-old#91]
This is a nasty one, but for completeness sake, here it is...

When your authentication for office365.com is provided by another domain (ie - you are a business customer with your own active directory), the client cannot cope with 

This may just be documenting how to do it... or it may require code writing for it.

Tried the following combos, where my domain is "corporation.com", my email alias is a.dude, and my AD account name is dude ; all have various problems (either not a valid email address, or doesn't auth successfully)
- a.dude@corporation.com
- dude@corporation.com

The whole domain\user@domain thing works for the Android Exchange connector so I tried that
- corporation.com\dude@corporation.com
- corporation.com\a.dude@corporation.com

**Comment by xybu** [comment]
Office 365 uses another set of API, not OneDrive API. So this application cannot sync OneDrive Pro (Office 365).

**Comment by ghost** [comment]
Hi,

Not sure if you saw my email asking about “choose folders” option in the Windows version of the OneDrive application. There is an option to only sync certain folders. Is that something that is available with your application.

Thanks.

**Comment by xybu** [comment]
Something to ignore certain paths / file names is implemented as "ignore list", available since 1.0-dev.
