### ISSUE TITLE
command unknow

### ISSUE THREAD

**Issue by yann120** [xybu/onedrive-d-old#94]
Hi everyone,

I try to install onedrive-d on my raspberry pi to use it like a uploader on the cloud. 
but I have a problem, i can't launch it after i install it
It say in french : commande introuvable
It mean that the command can't be found.
I copy the text of the installation : 
pi@raspberrypi ~/onedrive-d $ ./setup.sh inst
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances  
Lecture des informations d'état... Fait
git est déjà la plus récente version disponible.
inotify-tools est déjà la plus récente version disponible.
python3-pip est déjà la plus récente version disponible.
python3-gi est déjà la plus récente version disponible.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 33 non mis à jour.
running install
Checking .pth file support in /usr/local/lib/python3.2/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.2/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating onedrive_d.egg-info
writing requirements to onedrive_d.egg-info/requires.txt
writing onedrive_d.egg-info/PKG-INFO
writing top-level names to onedrive_d.egg-info/top_level.txt
writing dependency_links to onedrive_d.egg-info/dependency_links.txt
writing manifest file 'onedrive_d.egg-info/SOURCES.txt'
warning: manifest_maker: standard file 'setup.py' not found

reading manifest file 'onedrive_d.egg-info/SOURCES.txt'
writing manifest file 'onedrive_d.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv6l/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/onedrive_d
copying onedrive_d/pref_gtk.py -> build/lib/onedrive_d
copying onedrive_d/config.py -> build/lib/onedrive_d
copying onedrive_d/daemon.py -> build/lib/onedrive_d
copying onedrive_d/observer_gtk.py -> build/lib/onedrive_d
copying onedrive_d/live_api.py -> build/lib/onedrive_d
copying onedrive_d/logger.py -> build/lib/onedrive_d
copying onedrive_d/main.py -> build/lib/onedrive_d
copying onedrive_d/pref_cmd.py -> build/lib/onedrive_d
copying onedrive_d/**init**.py -> build/lib/onedrive_d
copying onedrive_d/setup.py -> build/lib/onedrive_d
copying onedrive_d/pref.py -> build/lib/onedrive_d
creating build/lib/onedrive_d/res
copying onedrive_d/res/icon_256.png -> build/lib/onedrive_d/res
copying onedrive_d/res/icon_256_idle.png -> build/lib/onedrive_d/res
creating build/bdist.linux-armv6l
creating build/bdist.linux-armv6l/egg
creating build/bdist.linux-armv6l/egg/onedrive_d
copying build/lib/onedrive_d/pref_gtk.py -> build/bdist.linux-armv6l/egg/onedrive_d
copying build/lib/onedrive_d/config.py -> build/bdist.linux-armv6l/egg/onedrive_d
copying build/lib/onedrive_d/daemon.py -> build/bdist.linux-armv6l/egg/onedrive_d
copying build/lib/onedrive_d/observer_gtk.py -> build/bdist.linux-armv6l/egg/onedrive_d
copying build/lib/onedrive_d/live_api.py -> build/bdist.linux-armv6l/egg/onedrive_d
copying build/lib/onedrive_d/logger.py -> build/bdist.linux-armv6l/egg/onedrive_d
copying build/lib/onedrive_d/main.py -> build/bdist.linux-armv6l/egg/onedrive_d
copying build/lib/onedrive_d/pref_cmd.py -> build/bdist.linux-armv6l/egg/onedrive_d
creating build/bdist.linux-armv6l/egg/onedrive_d/res
copying build/lib/onedrive_d/res/icon_256.png -> build/bdist.linux-armv6l/egg/onedrive_d/res
copying build/lib/onedrive_d/res/icon_256_idle.png -> build/bdist.linux-armv6l/egg/onedrive_d/res
copying build/lib/onedrive_d/**init**.py -> build/bdist.linux-armv6l/egg/onedrive_d
copying build/lib/onedrive_d/setup.py -> build/bdist.linux-armv6l/egg/onedrive_d
copying build/lib/onedrive_d/pref.py -> build/bdist.linux-armv6l/egg/onedrive_d
byte-compiling build/bdist.linux-armv6l/egg/onedrive_d/pref_gtk.py to pref_gtk.cpython-32.pyc
byte-compiling build/bdist.linux-armv6l/egg/onedrive_d/config.py to config.cpython-32.pyc
byte-compiling build/bdist.linux-armv6l/egg/onedrive_d/daemon.py to daemon.cpython-32.pyc
byte-compiling build/bdist.linux-armv6l/egg/onedrive_d/observer_gtk.py to observer_gtk.cpython-32.pyc
byte-compiling build/bdist.linux-armv6l/egg/onedrive_d/live_api.py to live_api.cpython-32.pyc
byte-compiling build/bdist.linux-armv6l/egg/onedrive_d/logger.py to logger.cpython-32.pyc
byte-compiling build/bdist.linux-armv6l/egg/onedrive_d/main.py to main.cpython-32.pyc
byte-compiling build/bdist.linux-armv6l/egg/onedrive_d/pref_cmd.py to pref_cmd.cpython-32.pyc
byte-compiling build/bdist.linux-armv6l/egg/onedrive_d/**init**.py to **init**.cpython-32.pyc
byte-compiling build/bdist.linux-armv6l/egg/onedrive_d/setup.py to setup.cpython-32.pyc
byte-compiling build/bdist.linux-armv6l/egg/onedrive_d/pref.py to pref.cpython-32.pyc
creating build/bdist.linux-armv6l/egg/EGG-INFO
copying onedrive_d.egg-info/PKG-INFO -> build/bdist.linux-armv6l/egg/EGG-INFO
copying onedrive_d.egg-info/SOURCES.txt -> build/bdist.linux-armv6l/egg/EGG-INFO
copying onedrive_d.egg-info/dependency_links.txt -> build/bdist.linux-armv6l/egg/EGG-INFO
copying onedrive_d.egg-info/requires.txt -> build/bdist.linux-armv6l/egg/EGG-INFO
copying onedrive_d.egg-info/top_level.txt -> build/bdist.linux-armv6l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
onedrive_d.**pycache**.setup.cpython-32: module references **file**
onedrive_d.**pycache**.observer_gtk.cpython-32: module references **file**
creating dist
creating 'dist/onedrive_d-1.0_dev-py3.2.egg' and adding 'build/bdist.linux-armv6l/egg' to it
removing 'build/bdist.linux-armv6l/egg' (and everything under it)
Processing onedrive_d-1.0_dev-py3.2.egg
removing '/usr/local/lib/python3.2/dist-packages/onedrive_d-1.0_dev-py3.2.egg' (and everything under it)
creating /usr/local/lib/python3.2/dist-packages/onedrive_d-1.0_dev-py3.2.egg
Extracting onedrive_d-1.0_dev-py3.2.egg to /usr/local/lib/python3.2/dist-packages
onedrive-d 1.0-dev is already the active version in easy-install.pth

Installed /usr/local/lib/python3.2/dist-packages/onedrive_d-1.0_dev-py3.2.egg
Processing dependencies for onedrive-d==1.0-dev
Searching for Send2Trash==1.3.0
Best match: Send2Trash 1.3.0
Processing Send2Trash-1.3.0-py3.2.egg
Send2Trash 1.3.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.2/dist-packages/Send2Trash-1.3.0-py3.2.egg
Searching for certifi==14.05.14
Best match: certifi 14.05.14
Processing certifi-14.05.14-py3.2.egg
certifi 14.05.14 is already the active version in easy-install.pth

Using /usr/local/lib/python3.2/dist-packages/certifi-14.05.14-py3.2.egg
Searching for urllib3==1.9.1
Best match: urllib3 1.9.1
Processing urllib3-1.9.1-py3.2.egg
urllib3 1.9.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.2/dist-packages/urllib3-1.9.1-py3.2.egg
Searching for requests==2.4.3
Best match: requests 2.4.3
Processing requests-2.4.3-py3.2.egg
requests 2.4.3 is already the active version in easy-install.pth

Using /usr/local/lib/python3.2/dist-packages/requests-2.4.3-py3.2.egg
Finished processing dependencies for onedrive-d==1.0-dev
running clean

Please issue command 'onedrive-pref [--no-gui]' to configure the app,
and then issue command 'onedrive-d' to start the daemon.
All operations finished.
pi@raspberrypi ~/onedrive-d $ onedrive-d
bash: onedrive-d : commande introuvable
pi@raspberrypi ~/onedrive-d $ cd
pi@raspberrypi ~ $ onedrive-d
bash: onedrive-d : commande introuvable
pi@raspberrypi ~ $ ^C
pi@raspberrypi ~ $ onedrive-pref [--no-gui]
bash: onedrive-pref : commande introuvable
pi@raspberrypi ~ $ onedrive-pref [--no-gui]
bash: onedrive-pref : commande introuvable
pi@raspberrypi ~ $ cd ./onedrive-d
pi@raspberrypi ~/onedrive-d $ onedrive-pref [--no-gui]
bash: onedrive-pref : commande introuvable
pi@raspberrypi ~/onedrive-d $ onedrive-pref --no-gui
bash: onedrive-pref : commande introuvable
pi@raspberrypi ~/onedrive-d $ cd
pi@raspberrypi ~ $ onedrive-pref --no-gui
bash: onedrive-pref : commande introuvable

Thanks,
Yann

**Comment by xybu** [comment]
#65

**Comment by yann120** [comment]
Oh thanks :) 
I've launched it!
I try to upload new files on onedrive but i have some problems.
Is there a command for upload directly a file or a folder ? like Upload /pi/doc/
Thanks for your amazing work!

**Comment by xybu** [comment]
For command-line interfaces, you may want to try `mk-fg/python-onedrive`.
