### ISSUE TITLE
Full Sync every time

### ISSUE THREAD

**Issue by punkymuzzle** [xybu/onedrive-d-old#96]
Hi
Great tool, but has a minor issue.
I have installed onto Ubuntu 14.04 LTS (64 bit) and it is running fine.  However, I have 2 issues:
1.  Whenever I start my PC the tool performs a full sync to Onedrive, rather than just uploading any changed files.  Not sure if anyone else has this problem.
2. The installation instructions show an icon in the notification bar showing sync progress.  This does not appear on my PC (although I still see the notifications popping up on my desktop when a file has synchronised)

Any additional information required please ask.
Keep up the good work.

Thanks

**Comment by Dutchglory** [comment]
Well doesn't sync everything, it stops after 2 minutes ... (in my case)
Op 12 dec. 2014 13:08 schreef "punkymuzzle" notifications@github.com:

**Comment by punkymuzzle** [comment]
As well as it is doing a full sync every time, it also appears to be creating additional copies of the same files every time it syncs.  I now have 3 copies of the same data on onedrive (2 copies with "[number]older" extension).
So as far as I am concerned this is not quite ready for use (in my particular case), so I have uninstalled it until it becomes more mature.

In the meantime I am using copy (copy.com) as an alternative.  This has a mature GUI and back end, and works well on Linux and WIndows (the 2 platforms I need to sync between).
If anyone is interested, here's my referral URL, which will get you an additional 5GB of additional storage (making a total of 20GB in total):
https://copy.com?r=YmC3qF

I'm not trying to hijack this thread with another product, just providing an alternative tool until the onedrive software is more developed and mature.

Good luck with the development of this, I wish you well.

**Comment by xybu** [comment]
Sounds like another victim of v0.85. You might want to check out the code in `future` branch (will be renamed soon, though; version number > 1.0). It has all the reported problems solved (or at least improved greatly).

BTW.. If you run both Windows machine and Linux machine, why not use BitTorrent Sync? The most lightweight solution I can find. Memory efficient. Fast. Free...

**Comment by punkymuzzle** [comment]
Hi
Thanks for the information.  I will take a look at  the latest version to see if it solves this.
Regarding BitTorrent Sync - this isn't what I want. BTSync is a peer to peer syncing tool with no cloud storage.  So that means:
1. I don't have an offsite copy of my data
2. I need both machines powered on at the same time to enable the Sync.  As I use my Linux box during the day and my Windows notebook in the evening they are typically on and off at different time.  So, no sync.

So I'll stick with an online sync tool which is a better fit for me personally.  Thanks for the suggestion though.

**Comment by xybu** [comment]
I see. Our scenarios are different. I have an almost-always-on Windows machine to sync with OneDrive. I used BTSync to pull my Windows OneDrive folder to Linux, and propagate changes between them. I personally don't want any third party to have a copy of my whole OneDrive data. So far OneDrive is the only (and last) free online storage solution that hasn't been compromised before. I no longer entrust other providers my files.

Another possible alternative is StorageMadeEasy. I don't like it though.

Sent from my Windows Phone
