### ISSUE TITLE
Renamed, duplicated files

### ISSUE THREAD

**Issue by hkoivuneva** [xybu/onedrive-d-old#97]
This renamed about 3000 files in my OneDrive and made duplicates of some. Now I saw the duplicates, then did a search on the files and pressed delete - but apparently it had also renamed files that it hadn't duplicated so I apparently deleted some stuff...gosh. I have no idea what I did delete and I guess I'll see that when I need those files again, like pics and code.

For example:
2012-01-28_21.14.51.png (NEWER_1327778318.79)
cc_20130428_114023.reg (NEWER_1367138506.05)
TeamViewer_Setup.exe (NEWER_1416845653.42) (OLDER_1416845653.42)

I guess I'll only be using OneDrive from Windows from now on.

**Comment by xybu** [comment]
Where did you get the package of an already obsolete, experimental version? The log indicates that it is a version of at least 6 months ago.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by knolly42** [comment]
Just discovered that the duplicates files are all lower resolution copies. All seem to be 2040 x 1536. 
I thought MS had removed the enforced resizing? if so this looks like an API issue.
I notice that python-onedrive cli https://github.com/mk-fg/python-onedrive/issues/34 has support for ignoring re-size when uploading. Perhaps that is not implemented here?

Also looks like the 'older' and 'newer' stuff is coming from components.py and fires when local and remote times on files differ. I suspect what's happening is the upload time is being compared to the updated time, and when that happens, the duplicates created are lower res.

**Comment by xybu** [comment]
Both problems (OLDER/NEWER mess, picture downsize) have been addressed in `1.0-dev` and `future`.

**Comment by hkoivuneva** [comment]
Awesome, how did you do it? Great news, thank you!

2015-02-23 12:05 GMT+02:00 Xiangyu Bu notifications@github.com:
