### ISSUE TITLE
Errono 13

### ISSUE THREAD

**Issue by bunchoftrees** [xybu/onedrive-d-old#98]
So, I can't select a folder apparently... Running Ubuntu 14.10 with the Master fork. Here's the output. 
Not really sure how to fix. 

alix@shc-v2:~$ onedrive-d
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/prefs.py", line 244, in save_settings
    f = open(CONF_PATH, "w")
IOError: [Errno 13] Permission denied: '/home/alix/.onedrive/user.conf'

**Comment by blacksector** [comment]
Try installing Python Version 3.X

I believe the onedrive-d requires Python 3 instead of 2.

**Comment by xybu** [comment]
Please uninstall 0.x version as #113, in particular,

```
sudo rm -rfv /home/alix/.onedrive
```

and install from source code in `1.0-dev` or better, `future`.
